// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuartzSample.Data;

#nullable disable

namespace QuartzSample.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240925170224_wejihr")]
    partial class wejihr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuartzSample.Models.Set", b =>
                {
                    b.Property<string>("K")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("V")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("K");

                    b.ToTable("Set");
                });
#pragma warning restore 612, 618
        }
    }
}
